from abc import ABC, abstractmethod

from core.datasets import GamePalsDataset
from core.knowledge.utils import UserCommandInfo


class GamePalsTeacher(ABC):
    """
    GamePalsTeacher is the abstract base class for all Teachers
    in the Knowledge Distillation process of GamePals LLMs.

    :ivar GamePalsDataset game_states: the dataset of game states from which the teacher should elicit their knowledge
    :ivar list[UserCommandInfo] user_commands: the list of commands generated by the teacher from the game states
    :ivar list[str] labels: the list of outputs, each associated to a user command (and its game state)
    """

    def __init__(self, game_states: GamePalsDataset):
        """
        Creates a GamePalsTeacher.

        :param game_states: the dataset of game states from which the teacher should elicit their knowledge
        """
        self.game_states = game_states
        self.user_commands: list[UserCommandInfo] = []
        self.labels: list[str] = []

    @abstractmethod
    def generate_user_commands(self, prompt: str):
        """
        Generates user commands for the game states in self.game_states, using the given prompt.
        The user commands are stored into self.user_commands, each associated to the game state it was
        generated for.

        :param prompt: the knowledge-elicitation prompt
        """
        pass

    @abstractmethod
    def generate_labels(self, prompt: str):
        """
        Generates labels for each user command (and the corresponding game state), using the given prompt.

        :param prompt: the task prompt
        """
        pass
