from dataclasses import dataclass


@dataclass
class UserCommandInfo:
    """
    Dataclass containing information about a user command
    generated by the Teacher model.

    :ivar str command: the generated user command
    :ivar int game_state_idx: the index of the game state from which the command was generated
    :ivar float explicitness: a measure of how explicitly the command asks for something
    :ivar float atomicity: a measure of how many atomic actions will likely be required to fulfill the command
    :ivar float contextuality: a measure of how relevant the game state is to the execution of the command
    """
    command: str
    game_state_idx: int
    explicitness: float
    atomicity: float
    contextuality: float
    intent: str
